# Use an official Python runtime as a parent image

FROM python:3.6.7

WORKDIR /metriky-collect

COPY . /metriky-collect

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r dockerfile-requirements-collect.txt

# Run command when the container launches. Parametr -u je pro unbuffered output prikazu print()
CMD ["python", "-u", "pistat.py", "-r", "-w60"]
