# Use an official Python runtime as a parent image

FROM python:3.6.7

WORKDIR /metriky-makepages

COPY . /metriky-makepages

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r dockerfile-requirements-makepages.txt

# Run command when the container launches. Parametr -u je pro unbuffered output prikazu print()
# stranky generuj do /metriky-output
CMD ["python", "-u", "makepages.py", "-r", "-o/metriky-output", "-w600"]
